### PR TITLE
Re-added Benchmark project

### PR DESCRIPTION
**Pull request by gumbarros**
// * Summary *

BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.3672/23H2/2023Update/SunValley3)
13th Gen Intel Core i5-1335U, 1 CPU, 12 logical and 10 physical cores
.NET SDK 8.0.300
  [Host]     : .NET 6.0.30 (6.0.3024.21525), X64 RyuJIT AVX2
  DefaultJob : .NET 6.0.30 (6.0.3024.21525), X64 RyuJIT AVX2

| Method                   | Mean      | Error     | StdDev    | Median    | Rank | Gen0   | Gen1   | Allocated |
|------------------------- |----------:|----------:|----------:|----------:|-----:|-------:|-------:|----------:|
| SimpleParlotExpression   |  6.641 us | 0.1327 us | 0.3588 us |  6.554 us |    1 | 0.1678 |      - |   1.05 KB |
| SimpleAntlrExpression    | 10.407 us | 0.2471 us | 0.6968 us | 10.184 us |    2 | 2.1667 | 0.0916 |  13.34 KB |
| AdvancedParlotExpression | 16.633 us | 0.2681 us | 0.2239 us | 16.665 us |    3 | 0.3967 |      - |   2.58 KB |
| AdvancedAntlrExpression  | 38.813 us | 2.1784 us | 6.4230 us | 36.300 us |    4 | 6.2256 | 0.6714 |  38.39 KB |

// * Warnings *
MultimodalDistribution
  LogicalExpressionFactoryBenchmark.AdvancedAntlrExpression: Default -> It seems that the distribution can have several modes (mValue = 2.98)

### CODE REVIEW

**Comment by gumbarros** [comment]
WIP: I will do tonight Evaluate vs Lambda, need to go now

**Comment by gumbarros** [comment]
Another idea, add to the docs benchmark results

**Comment by Bykiev** [comment]
Can we run it on CI?

**Comment by gumbarros** [comment]
> Can we run it on CI?

What will be the objective on CI? Just output it? Update the docs markdown?

**Comment by gumbarros** [comment]
BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.3672/23H2/2023Update/SunValley3)
13th Gen Intel Core i5-1335U, 1 CPU, 12 logical and 10 physical cores
.NET SDK 8.0.300
  [Host]     : .NET 8.0.5 (8.0.524.21615), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.5 (8.0.524.21615), X64 RyuJIT AVX2


| Method                   | Mean           | Error       | StdDev      | Rank | Gen0   | Gen1   | Allocated |
|------------------------- |---------------:|------------:|------------:|-----:|-------:|-------:|----------:|
| LambdaWithoutCompilation |      0.3599 ns |   0.0110 ns |   0.0103 ns |    1 |      - |      - |         - |
| Evaluate                 |    466.6933 ns |   3.7975 ns |   3.5522 ns |    2 | 0.2842 | 0.0005 |    1784 B |
| LambdaWithCompilation    | 10,019.4714 ns | 114.7367 ns | 107.3247 ns |    3 | 0.7935 | 0.7629 |    5024 B |

// * Warnings *
MultimodalDistribution
  EvaluateVsLambdaBenchmark.LambdaWithoutCompilation: Default -> It seems that the distribution can have several modes (mValue = 2.89)

// * Legends *
  Mean      : Arithmetic mean of all measurements
  Error     : Half of 99.9% confidence interval
  StdDev    : Standard deviation of all measurements
  Rank      : Relative position of current benchmark mean among all benchmarks (Arabic style)
  Gen0      : GC Generation 0 collects per 1000 operations
  Gen1      : GC Generation 1 collects per 1000 operations
  Allocated : Allocated memory per single operation (managed only, inclusive, 1KB = 1024B)
  1 ns      : 1 Nanosecond (0.000000001 sec)

**Comment by gumbarros** [comment]
@Bykiev I added benchmarks to the docs, how to run and a warning about lambda performance. After some Google search, I see not point in adding benchmarks to CI because it would be very slow to run at the pipeline and don't know how we can automatically know if something is wrong.  If you have ideas on how to do this and the benefits, I'm open to add to the pipeline.

**Comment by Bykiev** [comment]
> > Can we run it on CI?
> 
> What will be the objective on CI? Just output it? Update the docs markdown?

Just the output, I don't think it's a good idea to update the docs

**Review by Bykiev — APPROVED** [review]

**Comment by gumbarros** [comment]
> > > Can we run it on CI?
> > 
> > 
> > What will be the objective on CI? Just output it? Update the docs markdown?
> 
> Just the output, I don't think it's a good idea to update the docs

Good idea, will create another PR to check if everything is alright

**Pull request merged**
