### PR TITLE
Do not convert external function name to lower case when ExpressionOptions.IgnoreCase option is used

### PR DESCRIPTION
**Pull request by Bykiev**
This PR removes convertion of external function name to lower case when ExpressionOptions.IgnoreCase option is used. The original function name will be passed to custom function evalution. You should handle this logic in your application.

It's a breaking change.

Closes [#168](https://github.com/ncalc/ncalc/issues/168)

### CODE REVIEW

**Comment by gumbarros** [comment]
Nice work, should this be v5 or v4.2? `master` version.json file is pointing to a future v4.2

**Review by gumbarros — APPROVED** [review]

**Comment by Bykiev** [comment]
Don't know exactly, but I think we can release it in v4.2. I believe it has a low impact as in most cases it's already handled in external application

**Comment by gumbarros** [comment]
Agree, as this don't affect source code and just runtime. Please update `CHANGELOG.MD` and we are ready.

**Comment by Bykiev** [comment]
Thank you, done

**Pull request merged**
