### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by Bykiev**
Updated `Parlot` and `PolySharp` packages

### CODE REVIEW

**Comment by Bykiev** [comment]
According to Parlot's changelog the performance should be improved, but the benchmarks shows degraded performance.
@sebastienros, can you please check what's wrong?

**Comment by sebastienros** [comment]
Haven't had time to check for perf so far, but still intend to. Also wondering if ncalc could use the new configuration knobs for parsing numbers... or maybe it's not possible because of BingInt? That could be extensible because I made it so if the type implements the new `INumber`.

**Comment by sebastienros** [comment]
Identified the bug in Parlot that makes the tests failed. But found another one that is breaking YesSql so I will release a new version when both are fixed.

**Comment by sebastienros** [comment]
@gumbarros I think it's also faster (I compared the Benchmarks actions with the previous build).

**Comment by sebastienros** [comment]
Another side effect, is that the compiled mode (for Parlot), when enabled, would take a long time to build the parser, like 10 seconds. I identified the issue in Parlot and fixed it with this version. I ran the tests and all passed. Maybe it would be useful to run the tests with compilation too, at least in PRs by setting a flag.

**Pull request merged**
