### PR TITLE
Add missing Ncalc.Benchmarks project to sln

### PR DESCRIPTION
**Pull request by Bykiev**
Add missing Ncalc.Benchmarks project to sln

### CODE REVIEW

**Comment by gumbarros** [comment]
Before merging, I think we should study on how to make the Benchmark work with both .csproj and NuGet version. I 100% agree to the benchmark be add the .sln, but if we compile the solution in debug or release and not SignedRelease, it cause errors (specifically at CI)

**Comment by Bykiev** [comment]
I've made it draft and opened an issue https://github.com/dotnet/BenchmarkDotNet/issues/2574

**Comment by Bykiev** [comment]
As InProcess toolchain is not supporting benchmarking with NuGet package we can run it on CI when building separate executables

**Comment by gumbarros** [comment]
Superseded by #220

**Pull request closed without merging**
