### PR TITLE
Add support for using null with operators

### PR DESCRIPTION
**Pull request by Bykiev**
This PR adds support for using null with operators. In this case null value will be returned instead of InvalidOperationException. This is a breaking change

### CODE REVIEW

**Comment by Bykiev** [comment]
Related discussion: https://github.com/ncalc/ncalc/discussions/183

**Comment by gumbarros** [comment]
If someone types 2 + null, the equivalent is 2 or null? Because 2 + 0 = 2

**Comment by Bykiev** [comment]
> If someone types 2 + null, the equivalent is 2 or null? Because 2 + 0 = 2

Any operation with null will return null value

**Comment by gumbarros** [comment]
> > If someone types 2 + null, the equivalent is 2 or null? Because 2 + 0 = 2
> 
> Any operation with null will return null value

image


Sorry, makes total sense

**Pull request merged**
