### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by Bykiev**
This PR just cleans the code. Unfortunately, I didn't find any `editorconfig` rules to enable or disable indent on new lines

### CODE REVIEW

**Comment by Bykiev** [comment]
@gumbarros, can you please test in your IDE the `trim_trailing_whitespace` setting with a new line? This seems to be not working in VS and on code cleanup it's always removes spaces in empty lines

**Comment by gumbarros** [comment]
Is f5a6329 ok?

**Comment by Bykiev** [comment]
> Is [f5a6329](https://github.com/ncalc/ncalc/commit/f5a6329eac5fd260d306416a53fd50029250f246) ok?

Looks good, is this with editorconfig from my PR?

**Comment by gumbarros** [comment]
> > Is [f5a6329](https://github.com/ncalc/ncalc/commit/f5a6329eac5fd260d306416a53fd50029250f246) ok?
> 
> Looks good, is this with editorconfig from my PR?

Yes. I think both Rider and VS uses editorconfig normally.
image

**Review by gumbarros — APPROVED** [review]

**Pull request merged**
