### PR TITLE
Improve error detection

### LINKED ISSUE #195: Improve error detection
image

### PR DESCRIPTION
**Pull request by gumbarros**
This closes #195

### CODE REVIEW

**Comment by gumbarros** [comment]
Help wanted, tried to refactor associative parsers but no success

**Comment by Bykiev** [comment]
I think we should use `Recursive` parser and check for operator sequence

**Comment by Bykiev** [comment]
I've tried to add this check to parser with no luck. Basically, we need a predefined list of operators, extract the operators from expression and check if they're valid. But can't make it with Parlot too...

**Comment by Bykiev** [comment]
@gumbarros, can you please review my changes? Looking good for me, please not, such type of expressions are still valid:

**Comment by gumbarros** [comment]
LGTM

**Comment by Bykiev** [comment]
No problem! I did some benchmarking of v4.2 and seems we have a performance drop up to 1.5x

```
BenchmarkDotNet v0.13.12, Windows 10 (10.0.19044.2965/21H2/November2021Update)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK 8.0.205
  [Host] : .NET 6.0.30 (6.0.3024.21525), X64 RyuJIT AVX2

Job=ShortRun  IterationCount=3  LaunchCount=1
WarmupCount=3

| Method                        | Runtime              | Categories             | Mean      | Error      | StdDev    | Rank | Gen0   | Allocated |
|------------------------------ |--------------------- |----------------------- |----------:|-----------:|----------:|-----:|-------:|----------:|
| NuGet_EvaluateCustomFunction  | .NET Framework 4.6.2 | EvaluateCustomFunction |  6.323 us |  1.6067 us | 0.0881 us |    1 | 0.3738 |   1.55 KB |
| NuGet_EvaluateCustomFunction  | .NET 8.0             | EvaluateCustomFunction |  6.522 us |  0.8646 us | 0.0474 us |    2 | 0.3738 |   1.55 KB |
| CsProj_EvaluateCustomFunction | .NET Framework 4.6.2 | EvaluateCustomFunction |  8.760 us |  3.0202 us | 0.1655 us |    3 | 0.3967 |   1.65 KB |
| CsProj_EvaluateCustomFunction | .NET 8.0             | EvaluateCustomFunction |  9.259 us |  4.2683 us | 0.2340 us |    4 | 0.3967 |   1.65 KB |
| NuGet_SimpleExpression        | .NET Framework 4.6.2 | SimpleExpression       | 16.897 us | 17.1650 us | 0.9409 us |    5 | 1.0376 |   4.36 KB |
| NuGet_SimpleExpression        | .NET 8.0             | SimpleExpression       | 17.261 us | 19.2293 us | 1.0540 us |    6 | 1.0376 |   4.36 KB |
| NuGet_EvaluateParameters      | .NET Framework 4.6.2 | EvaluateParameters     | 20.965 us |  6.4765 us | 0.3550 us |    7 | 1.2817 |    5.3 KB |
| CsProj_SimpleExpression       | .NET Framework 4.6.2 | SimpleExpression       | 21.320 us |  3.6165 us | 0.1982 us |    8 | 1.0681 |   4.48 KB |
| CsProj_SimpleExpression       | .NET 8.0             | SimpleExpression       | 21.340 us |  4.6534 us | 0.2551 us |    8 | 1.0681 |   4.48 KB |
| NuGet_EvaluateParameters      | .NET 8.0             | EvaluateParameters     | 21.466 us |  8.8353 us | 0.4843 us |    8 | 1.2817 |    5.3 KB |
| CsProj_EvaluateParameters     | .NET 8.0             | EvaluateParameters     | 28.830 us | 18.4606 us | 1.0119 us |    9 | 1.3428 |   5.55 KB |
| CsProj_EvaluateParameters     | .NET Framework 4.6.2 | EvaluateParameters     | 30.052 us | 17.5157 us | 0.9601 us |   10 | 1.3428 |   5.55 KB |
```

**Comment by Bykiev** [comment]
> No problem! I did some benchmarking of v4.2 and seems we have a performance drop up to 1.5x
> 
> ```
> BenchmarkDotNet v0.13.12, Windows 10 (10.0.19044.2965/21H2/November2021Update)
> Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
> .NET SDK 8.0.205
>   [Host] : .NET 6.0.30 (6.0.3024.21525), X64 RyuJIT AVX2
> 
> Job=ShortRun  IterationCount=3  LaunchCount=1
> WarmupCount=3
> 
> | Method                        | Runtime              | Categories             | Mean      | Error      | StdDev    | Rank | Gen0   | Allocated |
> |------------------------------ |--------------------- |----------------------- |----------:|-----------:|----------:|-----:|-------:|----------:|
> | NuGet_EvaluateCustomFunction  | .NET Framework 4.6.2 | EvaluateCustomFunction |  6.323 us |  1.6067 us | 0.0881 us |    1 | 0.3738 |   1.55 KB |
> | NuGet_EvaluateCustomFunction  | .NET 8.0             | EvaluateCustomFunction |  6.522 us |  0.8646 us | 0.0474 us |    2 | 0.3738 |   1.55 KB |
> | CsProj_EvaluateCustomFunction | .NET Framework 4.6.2 | EvaluateCustomFunction |  8.760 us |  3.0202 us | 0.1655 us |    3 | 0.3967 |   1.65 KB |
> | CsProj_EvaluateCustomFunction | .NET 8.0             | EvaluateCustomFunction |  9.259 us |  4.2683 us | 0.2340 us |    4 | 0.3967 |   1.65 KB |
> | NuGet_SimpleExpression        | .NET Framework 4.6.2 | SimpleExpression       | 16.897 us | 17.1650 us | 0.9409 us |    5 | 1.0376 |   4.36 KB |
> | NuGet_SimpleExpression        | .NET 8.0             | SimpleExpression       | 17.261 us | 19.2293 us | 1.0540 us |    6 | 1.0376 |   4.36 KB |
> | NuGet_EvaluateParameters      | .NET Framework 4.6.2 | EvaluateParameters     | 20.965 us |  6.4765 us | 0.3550 us |    7 | 1.2817 |    5.3 KB |
> | CsProj_SimpleExpression       | .NET Framework 4.6.2 | SimpleExpression       | 21.320 us |  3.6165 us | 0.1982 us |    8 | 1.0681 |   4.48 KB |
> | CsProj_SimpleExpression       | .NET 8.0             | SimpleExpression       | 21.340 us |  4.6534 us | 0.2551 us |    8 | 1.0681 |   4.48 KB |
> | NuGet_EvaluateParameters      | .NET 8.0             | EvaluateParameters     | 21.466 us |  8.8353 us | 0.4843 us |    8 | 1.2817 |    5.3 KB |
> | CsProj_EvaluateParameters     | .NET 8.0             | EvaluateParameters     | 28.830 us | 18.4606 us | 1.0119 us |    9 | 1.3428 |   5.55 KB |
> | CsProj_EvaluateParameters     | .NET Framework 4.6.2 | EvaluateParameters     | 30.052 us | 17.5157 us | 0.9601 us |   10 | 1.3428 |   5.55 KB |
> ```

I've made a benchmark again and now the results are almost the same, Don't know what caused such results

**Comment by gumbarros** [comment]
> > No problem! I did some benchmarking of v4.2 and seems we have a performance drop up to 1.5x
> > ```
> > BenchmarkDotNet v0.13.12, Windows 10 (10.0.19044.2965/21H2/November2021Update)
> > Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
> > .NET SDK 8.0.205
> >   [Host] : .NET 6.0.30 (6.0.3024.21525), X64 RyuJIT AVX2
> > 
> > Job=ShortRun  IterationCount=3  LaunchCount=1
> > WarmupCount=3
> > 
> > | Method                        | Runtime              | Categories             | Mean      | Error      | StdDev    | Rank | Gen0   | Allocated |
> > |------------------------------ |--------------------- |----------------------- |----------:|-----------:|----------:|-----:|-------:|----------:|
> > | NuGet_EvaluateCustomFunction  | .NET Framework 4.6.2 | EvaluateCustomFunction |  6.323 us |  1.6067 us | 0.0881 us |    1 | 0.3738 |   1.55 KB |
> > | NuGet_EvaluateCustomFunction  | .NET 8.0             | EvaluateCustomFunction |  6.522 us |  0.8646 us | 0.0474 us |    2 | 0.3738 |   1.55 KB |
> > | CsProj_EvaluateCustomFunction | .NET Framework 4.6.2 | EvaluateCustomFunction |  8.760 us |  3.0202 us | 0.1655 us |    3 | 0.3967 |   1.65 KB |
> > | CsProj_EvaluateCustomFunction | .NET 8.0             | EvaluateCustomFunction |  9.259 us |  4.2683 us | 0.2340 us |    4 | 0.3967 |   1.65 KB |
> > | NuGet_SimpleExpression        | .NET Framework 4.6.2 | SimpleExpression       | 16.897 us | 17.1650 us | 0.9409 us |    5 | 1.0376 |   4.36 KB |
> > | NuGet_SimpleExpression        | .NET 8.0             | SimpleExpression       | 17.261 us | 19.2293 us | 1.0540 us |    6 | 1.0376 |   4.36 KB |
> > | NuGet_EvaluateParameters      | .NET Framework 4.6.2 | EvaluateParameters     | 20.965 us |  6.4765 us | 0.3550 us |    7 | 1.2817 |    5.3 KB |
> > | CsProj_SimpleExpression       | .NET Framework 4.6.2 | SimpleExpression       | 21.320 us |  3.6165 us | 0.1982 us |    8 | 1.0681 |   4.48 KB |
> > | CsProj_SimpleExpression       | .NET 8.0             | SimpleExpression       | 21.340 us |  4.6534 us | 0.2551 us |    8 | 1.0681 |   4.48 KB |
> > | NuGet_EvaluateParameters      | .NET 8.0             | EvaluateParameters     | 21.466 us |  8.8353 us | 0.4843 us |    8 | 1.2817 |    5.3 KB |
> > | CsProj_EvaluateParameters     | .NET 8.0             | EvaluateParameters     | 28.830 us | 18.4606 us | 1.0119 us |    9 | 1.3428 |   5.55 KB |
> > | CsProj_EvaluateParameters     | .NET Framework 4.6.2 | EvaluateParameters     | 30.052 us | 17.5157 us | 0.9601 us |   10 | 1.3428 |   5.55 KB |
> > ```
> 
> I've made a benchmark again and now the results are almost the same, Don't know what caused such results

Probably hard to measure very small differences, and it's expected to be a little slowers because of new rules for the parser.

**Pull request merged**
