### PR TITLE
Added `IsDynamicCodeSupported` at .NET6+ apps

### LINKED ISSUE #199: AOT apps will not work with NCalc v4+
**Describe the bug**
Running NCalc.Play causes `System.PlatformNotSupportedException: Dynamic code generation is not supported on this platform.`, because NCalc.Play is AOT.

**Example Expression**
`1+1`

**Additional context**
We should allow an option to not compile the parser on AOT or an ifdef.

### PR DESCRIPTION
**Pull request by gumbarros**
This closes #199

### CODE REVIEW

**Comment by Bykiev** [comment]
Can you please make a benchmark for .NET Framework?

**Comment by Bykiev** [comment]
Can you please check your IDE, it seems it's not using `.editorconfig'

**Comment by gumbarros** [comment]
> Can you please check your IDE, it seems it's not using `.editorconfig'

I think my `.editorconfig` is fine, the file was probably unformatted before and I can't undo

image
image

**Comment by gumbarros** [comment]
> Can you please make a benchmark with and without Native AOT?

Sure, but probably AOT is slower because it don't have .Compile, and sebastien said .Compile improves performance. I will check tonight.

**Review by Bykiev — APPROVED** [review]

**Comment by gumbarros** [comment]
> I've tried to make a benchmark and it seems to be not supported with In-process toolchain. Nevermind, just merge this PR without benchmarking. It's expected slowdown with Native AOT enabled.

Thanks for checking, sorry again, pretty busy this week

**Comment by Bykiev** [comment]
> > I've tried to make a benchmark and it seems to be not supported with In-process toolchain. Nevermind, just merge this PR without benchmarking. It's expected slowdown with Native AOT enabled.
> 
> Thanks for checking, sorry again, pretty busy this week

No problem at all, thank your for your hard work!

**Pull request merged**
