### PR TITLE
Add support for ifs(cond, val, default)

### PR DESCRIPTION
**Pull request by baughj**
This PR adds support for  a new function`ifs()`, similar to `if()` but allows an arbitrary collection of `(condition, value)` pairs along with a default value if none of the conditions evaluate to true.

Examples:

`ifs([divider] != 0, [divided] / [divider], -1)` -> if `divider` != 0, return the value of `[divided] / [divider]`, otherwise return -1

I added unit tests for this as well, let me know if you think they need to be more comprehensive.

### CODE REVIEW

**Comment by baughj** [comment]
@yallie any thoughts on above?

**Comment by yallie** [comment]
Hi @baughj, 

sorry for my late reply!
Just got back from my vacation. 
Thanks for the PR, merging.

**Comment by baughj** [comment]
Awesome, thank you!

**Comment by baughj** [comment]
@yallie one thing - how do i go about updating documentation?

**Comment by yallie** [comment]
@baughj I'm not sure about wiki access rights here on github...

Please have a look at this wiki page: https://github.com/ncalc/ncalc/wiki/Functions
Do you see this `Edit` button in the upper-right corner?

image

**Comment by baughj** [comment]
Yep! It works. Sorry for the delay, I updated the documentation.

**Pull request merged**
