### PR TITLE
Added `LogicalExpressionList` and `in` operator

### LINKED ISSUE #236: Add `in` binary operator
**Is your feature request related to a problem? Please describe.**
Yes, I want to finally end once and for all usage from `DataTable.Compute`

**Describe the solution you'd like**
Allow `in` operator, supported by `DataTable.Compute`:
```
{PageState} in ('Update','Insert')
```

**Describe alternatives you've considered**
`in` function, but it's a breaking change for me, my system have more than 300 forms and will be impossible to check one by one to see if they have the `in` operator at the expressions

**Additional context**
Caution should be taken to not break the existing `in` function

### PR DESCRIPTION
**Pull request by gumbarros**
This closes #236.

This creates parity with `DataTable.Compute` where is possible to do the following expression for example:

"1 in (1,2,3)"

This PR brings two features:
- The `ArrayExpression` type,  that encapsulates a collection of `LogicalExpression`
- The `in` operator to check if an `ArrayExpression` contains the specified element.

Discussions for this PR:
- Should `ArrayExpression` be called this way? Should it store an array? Should it implement `IEnumerable`?
- Is the parser implementation correct at relational operators?

### CODE REVIEW

**Comment by Bykiev** [comment]
I like to see this feature in NCalc, good job! I think it should implement `IEnumerable` to be more consistent (like `IterateParameters` option)

**Comment by gumbarros** [comment]
@Bykiev I renamed to `LogicalExpressionList` and implemented `IList`, feels much more natural  to consume and the parsed list is index based.

One last question before merging is if the `in` operator is relational or not. Idk where it should be at the docs and the parser.

**Comment by gumbarros** [comment]
Impact on benchmarks, none:

| Method                   | Mean      | Error     | StdDev    | Rank | Gen0   | Allocated |
|------------------------- |----------:|----------:|----------:|-----:|-------:|----------:|
| SimpleParlotExpression   |  6.929 μs | 0.0150 μs | 0.0140 μs |    1 | 0.0076 |   1.02 KB |
| SimpleAntlrExpression    | 12.350 μs | 0.1006 μs | 0.0892 μs |    2 | 0.1526 |  13.38 KB |
| AdvancedParlotExpression | 18.910 μs | 0.0352 μs | 0.0312 μs |    3 | 0.0305 |   2.51 KB |
| AdvancedAntlrExpression  | 34.929 μs | 0.0887 μs | 0.0692 μs |    4 | 0.4272 |  38.47 KB |

**Review by Bykiev — APPROVED** [review]
LGTM

**Pull request merged**
