### PR TITLE
Update EvaluationVisitor.cs

### PR DESCRIPTION
**Pull request by theebow**
Extending "plus" functionnality to manage right string for formula type : [number] + [string]

Usefull in the case of formula evaluator.

### CODE REVIEW

**Comment by gumbarros** [comment]
Good morning, you also need to update `AsyncEvaluationVisitor`

**Comment by theebow** [comment]
> Hi, can you please add a test case?

`    [Fact]
    public void EvaluateFormulaWithParameters()
    {
        var e = new Expression("[NOORDRE] + [RACINE]", CultureInfo.InvariantCulture);
        e.Parameters["RACINE"] = "X";
        e.Parameters["NOORDRE"] = 1;

        string myResult = e.Evaluate().ToString();
        System.Diagnostics.Debug.Assert(string.Compare("1X", myResult, true) == 0);
    }
`

This sample crash here : 
image

**Comment by theebow** [comment]
> Good morning, you also need to update `AsyncEvaluationVisitor`

i'm not github expert^^ but i'm going to try

**Comment by theebow** [comment]
> > Good morning, you also need to update `AsyncEvaluationVisitor`
> 
> i'm not github expert^^ but i'm going to try

@gumbarros i found how to, it's ok

**Comment by Bykiev** [comment]
This change is breaking. Before this change when the left value is not a string it'll try to convert right string or char parameter to number. On the one side, in C# it's possible to concat numbers and strings, on the other side - it can break the existing apps.

@gumbarros, what do you think?

**Comment by gumbarros** [comment]
> This change is breaking. Before this change when the left value is not a string it'll try to convert right string or char parameter to number. On the one side, in C# it's possible to concat numbers and strings and the result will be concatenated strings, on the other side - it can break the existing apps.
> 
> Upd. `1 + '1'` in C# results to 50, because it's getting a code of char. So, the behaviour of NCalc is different. I vote for stay it as is.
> 
> @gumbarros, what do you think?

Good points, maybe a `ExpressionOptions.CharAsNumber` so we can have both behaviors without breaking? Idk if it's worth.

**Comment by Bykiev** [comment]
But what to do if one of the parameters is number and another one is string? I think it should be `ExpressionOptions.StringAsNumber` and IIRC chars in NCalc always converted to strings. But anyway, it'll introduce a breaking change as we need to convert the right parameter to number if needed

**Comment by Bykiev** [comment]
@gumbarros, sould we introduce a new option or leave it as is, what do you think?

**Comment by gumbarros** [comment]
> @gumbarros, sould we introduce a new option or leave it as is, what do you think?

I still don't understand how it would work, is this the proposed behavior of the new option?

Without `ExpressionOptions.StringAsNumber`:

`1 + "1" = NCalcEvaluationException`

With `ExpressionOptions.StringAsNumber`:

`1 + "1" = 2`

**Comment by Bykiev** [comment]
> > @gumbarros, sould we introduce a new option or leave it as is, what do you think?
> 
> I still don't understand how it would work, is this the proposed behavior of the new option?
> 
> Without `ExpressionOptions.StringAsNumber`:
> 
> `1 + "1" = NCalcEvaluationException`
> 
> With `ExpressionOptions.StringAsNumber`:
> 
> `1 + "1" = 2`

I think we should name it `ExpressionOptions.StringConcat`, it should be working this way

```
if (options.HasFlag(ExpressionOptions.StringConcat))
{
    Result = string.Concat(leftValue.Value, rightValue.Value);
}
else
// try to convert to numbers
```

**Comment by gumbarros** [comment]
> > > @gumbarros, sould we introduce a new option or leave it as is, what do you think?
> > 
> > 
> > I still don't understand how it would work, is this the proposed behavior of the new option?
> > Without `ExpressionOptions.StringAsNumber`:
> > `1 + "1" = NCalcEvaluationException`
> > With `ExpressionOptions.StringAsNumber`:
> > `1 + "1" = 2`
> 
> I think we should name it `ExpressionOptions.StringConcat`, it should be working this way
> 
> ```
> if (options.HasFlag(ExpressionOptions.StringConcat))
> {
>     Result = string.Concat(leftValue.Value, rightValue.Value);
> }
> else
> // try to convert to numbers
> ```

With StringConcat 1+1 would become 11? Or just if one of the values are a string like '1' + 1 = 11?

**Comment by gumbarros** [comment]
> I think 1+1 should be "11" with StringConcat
Yes, what I was thinking, just missed the ". It's not a use case for me but as long this happens only when the option is enabled, I see no problem.

**Comment by Bykiev** [comment]
Of course, it's a breaking change again as "1" + 1 will be 2 (not "11" as now) without this option

**Comment by gumbarros** [comment]
> Of course, it's a breaking change again as "1" + 1 will be 2 (not "11" as now) without this option

I think it's more a fix than a breaking change 😄. But the "canon" CLR evaluation would be this right? 

image

**Comment by Bykiev** [comment]
If I remember correctly in NCalc chars are always treating as strings, if we want a CLR behaviour we need to introduce a bigger breaking changes 😄

**Comment by gumbarros** [comment]
> If I remember correctly in NCalc chars are always treating as strings, if we want a CLR behaviour we need to introduce a bigger breaking changes 😄

Makes sense, because there is no `ValueType.Char`, so I agree with what you proposed.

**Pull request closed without merging**
