### PR TITLE
Allow custom culture info fixes

### PR DESCRIPTION
**Pull request by rholek**
Fixes for https://github.com/ncalc/ncalc/pull/46. Culture info was not passed to all methods correctly.

### CODE REVIEW

**Comment by yallie** [comment]
Thanks for the PR @rholek!

Could you please add a couple of unit tests that demonstrate the difference?
I.e. a couple of expressions that doesn't calculate when cultureInfo is not specified but work fine if it's specified.
Something like this —

```csharp
[Test]
public void TestCultureInfo()
{
    // a culture-specific expression example
    var expr = "...";

    // throws if CultureInfo is not specified
    Assert.Throws<EvaluationExpression>(() => Expression.Evaluate(expr));

    // throws if CultureInfo is not the expected one
    Assert.Throws...

    // doesn't throw if CultureInfo is specified
    var result = ...
    Assert.AreEqual(..., result);
}
```

**Comment by rholek** [comment]
I added the test

**Comment by yallie** [comment]
Thank you @rholek! 👍

**Comment by rholek** [comment]
@yallie please publish this fix to nuget

**Comment by yallie** [comment]
Thanks @rholek, here is it —
https://www.nuget.org/packages/NCalcSync/3.4.0

**Pull request merged**
