### PR TITLE
Added `ExpressionOptions.AllowCharValues`

### PR DESCRIPTION
**Pull request by gumbarros**

### CODE REVIEW

**Review by Bykiev — COMMENTED** [review]
Should we override the logic for addition? Like CLR, 3 + '3' should be 51

**Comment by Bykiev** [comment]
Maybe a big breaking change would be better? Let's make the behaviour of NCalc to match the CLR:
```
3 + '3' = 51
"3" + 5 = "35"
5 + "3" = 53
```

**Comment by gumbarros** [comment]
> Maybe a big breaking change would be better? Let's make the behaviour of NCalc to match the CLR:
> 
> ```
> 3 + '3' = 51
> "3" + 5 = "35"
> 5 + "3" = "53"
> ```

Agree with the behavior, but it will be non-breaking, because `char` values are parsed only when `ExpressionOptions.AllowCharValues` is specified.

**Review by Bykiev — APPROVED** [review]

**Comment by gumbarros** [comment]
Something is still wrong. Sometimes the test pass and sometimes it fails, including in my machine.

**Comment by Bykiev** [comment]
> Something is still wrong. Sometimes the test pass and sometimes it fails, including in my machine.

Yes, seems smth is wrong, the merged PR also failed on CI

**Review by Bykiev — APPROVED** [review]

**Comment by gumbarros** [comment]
> > Something is still wrong. Sometimes the test pass and sometimes it fails, including in my machine.
> 
> Yes, seems smth is wrong, the merged PR also failed on CI

The `main` error it's just #238, everything is passed. But in this PR, `[InlineData("3 + '3'", ExpressionOptions.AllowCharValues,54)]` does not work in parallel executions but work at single executions.

**Comment by Bykiev** [comment]
As this is not related to this PR it should be addressed in another one, This PR can be merged

**Comment by gumbarros** [comment]
@Bykiev after some rest solved the error. It's because the expression `3 + '3'` is used two times at the unit tests and is cached. `ExpressionOptions.NoCache` solved the problem.

**Pull request merged**
