### PR TITLE
Add GetParametersNames method to Expression.cs

### LINKED ISSUE #103: How to get a list of all variables (or their names) used in an expression?
Alternatively: is it possible to make it so that if the value of some parameter was not defined, some default value would be used instead of throwing an exception?
Context: I'm using NCalc expressions as part of an in-game programming language, and I need to be sure that even if the user didn't set some variables before evaluating the expression, they'll get a result and not an error.

### PR DESCRIPTION
**Pull request by gumbarros**
This closes #103

### CODE REVIEW

**Comment by gumbarros** [comment]
@yallie you can also close PR #28 that does basically the same thing

**Comment by yallie** [comment]
Hi @gumbarros, thanks for the PR!

But what if an expression has custom functions?
Doesn't it list custom functions as parameters?

**Comment by gumbarros** [comment]
Hmmm, I will cover this in a unit test to be sure

**Comment by gumbarros** [comment]
@yallie everything looks fine, tried both custom functions and native functions

**Comment by yallie** [comment]
Thanks!

**Pull request merged**
