### PR TITLE
Fixed not operator behavior

### LINKED ISSUE #226: Breaking Change in 4.2.1 - not<nospace>(true) throws UnknownFunction
**Describe the bug**

The behavior has changed - expression with no space between not and a brace () throws a unknown function not.
Previos behavior was  'not ( true )' return false.
 

**Example Expression**
 'not( true )'  throws
 'not ( true )'  return false
 
 Should be added to Breaking Changes, or could not be handled as Operator instead function ?

### PR DESCRIPTION
**Pull request by gumbarros**
This closes #226

### CODE REVIEW

**Comment by gumbarros** [comment]
Don't know if it's the best way, but better than a custom function I think

**Comment by Bykiev** [comment]
Can you please add `not(true)` failing case in the test

**Comment by gumbarros** [comment]
> Can you please add `not(true)` failing case in the test

Weird why this fails ☠️, I think creating the custom function will do the job

**Comment by Bykiev** [comment]
Sure, but it'll be a breaking change as functions are case-sensitive, but operators not

**Comment by gumbarros** [comment]
> Sure, but it'll be a breaking change as functions are case-sensitive, but operators not

At ANTLR this works, weird, I see no problem in a function, but there should be a way at the parser

**Comment by Bykiev** [comment]
Definitly it's possible to fix it on parser side. As I can see after this it's getting `true)` and because of this it's not treated as group expression

**Comment by Bykiev** [comment]
I think it can be handled in a custom way in `Then` flow parser

**Review by Bykiev — APPROVED** [review]

**Comment by gumbarros** [comment]
@Bykiev thanks for the help

**Pull request merged**
